services:
  - type: web
    name: drapal-real-estate-2
    runtime: docker
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin_c46c5c17
      - key: ADMIN_PASSWORD
        value: 5b6ae6a70d753d8e
    disk:
      name: drapal-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1