services:
  - type: web
    name: drapal-real-estate-2  # Ujistěte se, že se to shoduje s názvem služby v Renderu
    runtime: node
    # ... zbytek konfigurace
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: drapal-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1